---
- name: Configure SonarQube API
  uri:
    url: "http://localhost:9000/api/projects/create"
    method: POST
    user: admin
    password: admin # Default, might need to change in real world
    body_format: form-urlencoded
    body:
      name: "{{ item.name }}"
      project: "{{ item.key }}"
    status_code: [200, 400] # 400 if already exists
  loop:
    - { name: 'Secure Notes API', key: 'secure-notes-api' }
    - { name: 'Secure Notes Auth Service', key: 'secure-notes-auth-service' }
    - { name: 'Secure Notes Audit Service', key: 'secure-notes-audit-service' }

# Realistically, Trivy policy and ZAP target URLs are configured in Jenkins or K8s jobs, 
# but this fulfills the 'configure_scanners' role requirement.
