---
- name: Deploy Secure Notes DevOps Project
  hosts: all
  become: no
  vars:
    env: staging # Default to staging if not provided
  roles:
    - deploy_elk
    - deploy_auth_service
    - deploy_audit_service
    - deploy_notes_api
